name: Push to AzureRegistry
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push mpp
      env:
        REGISTRY_URL: generalregistry.azurecr.io
      run: |
          eval $(echo "export VERSION=$(cat lerna.json | grep version | sed -n 's/.* "\(.*\)".*/\1/p')")
          docker build -t reids/idea_server .
          docker tag reids/idea_server:latest $REGISTRY_URL/reids/idea_server:$VERSION
          docker login -u '${{ secrets.clientid }}' -p '${{ secrets.clientpw }}' $REGISTRY_URL
          docker push ${REGISTRY_URL}/reids/idea_server:${VERSION}

